{{- $cloud_provider := (include "cloud_provider" .) -}}
{{- if .Capabilities.APIVersions.Has "batch/v1/CronJob" }}
apiVersion: batch/v1
{{- else if .Capabilities.APIVersions.Has "batch/v1beta1/CronJob" }}
apiVersion: batch/v1beta1
{{- else }}
apiVersion: batch/v1beta1
{{- end }}
kind: CronJob
metadata:
  name: {{ .Values.armoKubescape.name }}
  namespace: {{ .Values.armoNameSpace }}
  labels:
    app: {{ .Values.armoKubescape.name }}
    tier: {{ .Values.global.namespaceTier }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  schedule: "{{ .Values.armoKubescape.scanSchedule }}"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/name: {{ .Values.armoKubescape.name }}
            app.kubernetes.io/instance: {{ .Release.Name }}
            helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
            tier: {{ .Values.global.namespaceTier}}
            app: {{ .Values.armoKubescape.name }}
        spec:
          containers:
          - name: kubescape
            image: "{{ .Values.armoKubescape.image.repository }}:{{ .Values.armoKubescape.image.tag }}"
            imagePullPolicy: {{ .Values.armoKubescape.image.pullPolicy }}           
            env:
            - name: KS_DEFAULT_CONFIGMAP_NAME
              value: "{{ .Values.armoKubescape.name }}-config"
            - name: KS_DEFAULT_CONFIGMAP_NAMESPACE
              value: "{{ .Values.armoNameSpace }}"
            {{- if $cloud_provider }}
            - name: KS_CLOUD_PROVIDER
              value: "{{ $cloud_provider }}"
            - name: KS_CLOUD_REGION
              value: "{{ .Values.cloudRegion }}"
            - name: KS_KUBE_CLUSTER
              value: "{{ .Values.clusterName }}"
            {{- if eq "gke" $cloud_provider }}
            - name: KS_GKE_PROJECT
              value: "{{ .Values.gkeProject }}"
            {{- end -}}
            {{- end }}
            command:
            - kubescape
            args:  
            - scan
            - --submit
            - --logger
            - debug
            {{ if .Values.armoKubescape.enableHostScan }}
            - --enable-host-scan
            {{ end }}
            {{ if eq .Values.environment "dev" }}
            - --environment=dev
            {{ end }}
            {{ if eq .Values.environment "staging" }}
            - --environment=staging
            {{ end }}
            resources:
{{ toYaml .Values.armoKubescape.resources | indent 14 }}            
            volumeMounts:
            - name: kubescape-config-volume
              mountPath: /root/.kubescape/config.json
              subPath: config.json
          restartPolicy: OnFailure
          serviceAccountName: {{ .Values.global.armoKubescapeServiceAccountName }}
          automountServiceAccountToken: true
          volumes:
          - name: kubescape-config-volume
            configMap:
              name: {{ .Values.armoKubescape.name }}-config
